get http://localhost:5000/notes

###

POST  http://localhost:5000/tambahdata
Content-Type: application/json

{
    "nama":"ronaldo",
    "judul":"goal",
    "catatan":"siu, gol gol gol gol"
    
}



###

PUT http://localhost:5000/edit-user/3
Content-Type: application/json


{

    "judul": "siu"
}


###

DELETE  http://localhost:5000/delete-user/3



